### ISSUE TITLE
Can't delete a file if it wasn't assigned to a user or a group

### ISSUE THREAD

**Issue by bchhun** [ignacionelson/ProjectSend#9] opened 2014-10-07 02:03 UTC
I'm not sure whether this is a bug or a feature but here it goes.

Although a confirmation message is shown, it seems we can't delete a file if we didn't assigned it to a user or a group beforehand.

## Steps to reproduce it

1. Upload a file
2. Don't assign it to any user or group
3. Try to delete it using the table interface in **manage-file.php**

## Symptoms

There's no value attribute for the file's checkbox because the id comes from the **files_relations** table and we don't have any entry there...

And it stays that way during the whole deletion process until the confirmation message.

## Possible solutions

1. Show a warning message mentionning we need to assign a file before we can delete it
2. Don't use the **files_relations**'s file id and stick with the id from the **files** table

**Comment by strigga** [comment] 2015-02-04 13:24
i also can not delete files as a system administrator or other user.
Is there a solution?

**Comment by bchhun** [comment] 2015-02-04 16:04
@strigga yes. you need to assign the file you want to delete to a user or a group and then delete it.

**Comment by strigga** [comment] 2015-02-04 19:32
Thank you. This works!
But why does it not assign automatically to the user who has uploaded the file?

So if i have 50 files and want to delete it i have to click on every single file - assign it to a user and after that i can delete it?

**Comment by bchhun** [comment] 2015-02-05 21:48
My best guess is that you may upload files for other users and assign them whenever you want.

Yes for the mass deletion :)

**Comment by ignacionelson** [comment] 2015-06-08 05:25
r582 includes this fix. Closing the issue now.

**Closed by ignacionelson** 2015-06-08 05:25 UTC

**Comment by bchhun** [comment] 2015-06-09 19:52
+1

**Comment by ignacionelson** [comment] 2015-06-09 19:55
Have you tried the latest version? r582

**Comment by riczito** [comment] 2015-10-09 07:40
On r582 the problem still persists. As an admin, I cannot delete user files, whether they are assigned to users or not. As a user, I cannot delete my own files from my workspace. This is pretty essential functionality. Please help find a solution or workaround!

**Comment by tekopsinc** [comment] 2015-12-30 22:42
Yes, the problem still persists.  It does not delete the file(s) no matter what you do.  Version r582 confirmed.

**Comment by semaphorism** [comment] 2016-01-02 02:53
It looks like that $file_id in manage_files.php at line 537 is referencing the wrong ID (from tbl_files_relations rather than tbl_files as expected by the delete function).  My fix was to change line 537 to read:

`<td><input type="checkbox" name="files[]" value="<?php echo $row['id']; ?>" /></td>`

I can't remember if that's all I did to fix this problem, but it's a start.  Good luck.

**Comment by lenamtl** [comment] 2016-01-04 15:36
Do you have an error message, like please select one file?

**Comment by ashes00** [comment] 2016-01-21 21:19
semaphorism - I was able to make just the change that you mentioned, and it fixed my issue.  I was not able to delete ANY file before.  Now I can.  Thank you!
,Ash

**Comment by tekopsinc** [comment] 2016-05-30 00:55
We made the change (and it's manage-files.php, not manage_files.php) and it works great.  Thank you so much!

**Comment by luisalmeidarealbase** [comment] 2016-05-30 17:31
@semaphorism thank you for your solution. It worked! :D

**Comment by crashff00** [comment] 2016-08-12 18:58
This has once again come back in r611.   Any file not assigned to a user automatically gets removed from the file manager and put into the orphaned file list, 

You cannot delete any files located on the orphaned file list.  I believe this is now tied to the orphaned files list ( #107 ), or at least adding the ability to delete unassigned files directly.  (what happens if a wrong file is uploaded? the account admin cant remove the file without assigning it to a -USER-, which then triggers a file availability email if the user has this option set.
