### ISSUE TITLE
Logo image not shown

### ISSUE THREAD

**Issue by ASMoreira** [ignacionelson/ProjectSend#233] opened 2016-09-24 16:25 UTC
in index.php I diont have logo image. I have to change functions.php line 834 to 
		$branding_image = BASE_URI . $branding['url'];

**Comment by lenamtl** [comment] 2016-09-25 11:23
Instead
log as admin, go to option - thumbnail and check the checkbox of Use file's absolute path
see #199

**Comment by ASMoreira** [comment] 2016-09-25 12:20
This solve the problem.
This only happens if not installed in the root because there is a "/" in $branding['url'].
This also work fine
	$branding['url'] = 'img/custom/logo/'.LOGO_FILENAME;
	if (file_exists(ROOT_DIR."/".$branding['url'])) {

**Comment by aaronsheard** [comment] 2016-09-25 15:55
i tried checking abs path in thumbnail screen and it wont save, it says please complete all fields.

**Comment by lenamtl** [comment] 2016-09-25 16:50
Check others options tabs / pages to see if missing info are required.

**Comment by lenamtl** [comment] 2016-10-25 18:16
Something is wrong with your installation, you may try to reinstalled it from scratch.
I'm close this for now let me know if you still have issue

**Closed by lenamtl** 2016-10-25 18:16 UTC

**Comment by pjensen1977** [comment] 2017-04-03 12:59
Seems the problem is not fixed. Its showing the logo on the main login page, but as soon a user logs in he doesnt show the logo anymore. I tried using the absolute path setting, did not work (or change anything for that matter). I also tried ASMoreira comment, it did fix the double / when using the absolute path setting, but didnt help resolve the issue.

**Comment by lenamtl** [comment] 2017-04-03 14:31
This is a configuration issue.
Could you check in browser console if you have any errors....
Are you using https?
