### ISSUE TITLE
After all, does the customer receive a notification by mail when upload a file?

### ISSUE THREAD

**Issue by bugetarul** [ignacionelson/ProjectSend#395] opened 2017-04-24 18:40 UTC
Hello
After all, does the customer receive a notification by mail when upload a file?
When the customer make his  account check “Notify new uploads by e-mail”
but does not receive mail.
When the customer make upload appear the message “E-mail notifications have been sent.”But dont receive mail
The only mail receive is when the  customer make the account
Is an option not yet implemented? Or something is wrong?

**Comment by lenamtl** [comment] 2017-04-26 15:58
If you mean the client is not receiving the email notification when admin upload and assign a file to him:
Please check the options/settings how many times (attempts) it is set for email notification and increase the number of attempts.
Make sure the email message is not in spam folder.

**Comment by bugetarul** [comment] 2017-04-26 16:54
Hello
The client receiving notification when admin upload and assign a file to him. Is ok.
But not when he upload in his account. When the client finishes uploading this message appears: "E-mail notifications have been sent." But the email is not sent.

![error-mail](https://cloud.githubusercontent.com/assets/27968429/25446383/0de8ab36-2aba-11e7-82f7-fac083b59114.jpg)

**Comment by lenamtl** [comment] 2017-04-28 12:19
The client won't receive an email when he upload a file to his account.
I guess (we have to check into the code) the admin will received a message when client upload a file into his account. So does the admin received it?

Also you can try to increase send email attempts to higher number.
So when the system is trying to send an email if this is not sending for any reason, this wil try again depending of the number of attempts you have set.

**Comment by bugetarul** [comment] 2017-04-28 15:33
The problem is not at admin. Perhaps is announced, it does not matter

The problem is: When a user upload a message appears "E-mail notifications have been sent"
The message appears every time when the client upload. 
Customers will expect to receive mail. And they will cry that they do not receive it.
So either remove the message or send the emails. :)

I prefer to send mail because clients prefer to receive a receipt for they upload
Thank you

**Comment by ilackskills** [comment] 2017-04-28 17:00
This should be pretty easy to fix

**Comment by lenamtl** [comment] 2017-05-01 00:34
For the client this message should be hidden and appear only to system user.
.

**Comment by bugetarul** [comment] 2017-05-01 09:06
NO. at client, Those who make account from "Don't have an account yet? Register as a new client."

If you want, I can give you access to the system. Is still in tests

**Comment by ilackskills** [comment] 2017-05-02 14:54
The new user should get an email with username and password if you have the email configuration set correctly.

**Comment by lenamtl** [comment] 2017-05-02 16:20
Hi, sorry I don't understand this is very confusing first you are saying your client see a message when they upload file... Now you are talking about user registration.... 
Maybe you have a global issue when the system is trying to send an email message.

Make sure your installation & server are set correctly then do tests with different email account from different provider so you will find if this is general or not.

I will close this for now as it seems to be a configuration issue.
Also next time write step by step how to reproduce the problem and don't forget to mention roles involved.

**Closed by lenamtl** 2017-05-02 16:20 UTC
Labels: Enhancement, Question
