### ISSUE TITLE
Admin works, Clients don't

### ISSUE THREAD

**Issue by macintyres** [ignacionelson/ProjectSend#342] opened 2017-02-06 20:37 UTC
I can log in as admin and everything works as intended. When I attempt a login as a client, I'm directed to  /my_files/  
The page is empty.

**Comment by lenamtl** [comment] 2017-02-06 23:46
Verify if you have all files on your server it's seems that files are missing.

**Comment by macintyres** [comment] 2017-02-07 13:14
Checked my site with the current code repository and there is nothing missing.

**Comment by lenamtl** [comment] 2017-02-07 15:48
Which PHP version are you using?

**Comment by macintyres** [comment] 2017-02-07 16:04
7.0

**Comment by ilackskills** [comment] 2017-02-07 20:38
after log in as a client are you able to manually navigate to http://my-path/manage-files.php

**Comment by macintyres** [comment] 2017-02-07 21:27
After login, the browser goes to the correct path and shows up as a blank page. The same thing happens if I manually insert the path.

**Comment by macintyres** [comment] 2017-02-08 13:15
I did a fresh install, using the same Ubuntu 16.04 server. I made a new database and used a different directory. Install worked without a hitch. I could log in as admin and everything worked. I added a client, logged out and then logged in as the client and got blank (/my_files) page again.
Ubuntu 16.04.1
Apache  2.4.18
MySQL  5.7.17 
PHP 7.0.13

**Comment by ilackskills** [comment] 2017-02-09 05:31
@ilackskills confirm this is an issue. I will work on this after I fix the upload issue

**Comment by macintyres** [comment] 2017-02-13 13:34
I managed to get to a menu while logged in as a client by logging in, getting to the empty /my_files/ dir. then turning off apache server and turning it back on. I then manually entered an address that an admin would be able to access. This gave me a message saying I didn't have rights to access the page, but it gave me a menu bar. I found that, as a client, I could access the file upload and other client options. 
/my_files/ is still blank but the other areas are working for client level user.

**Comment by lenamtl** [comment] 2017-02-13 20:47
I cannot reproduce on regular install 5.6 
It is probably related to PHP7 or server configuration.

**Comment by patricksnead** [comment] 2017-02-13 21:42
I can confirm same behavior with my new installation using PHP 5.6
Using:
Debian 3.16.36-1+deb8u2
Apache/2.4.10 (Debian)
MySQL Server version: 5.5.54-0+deb8u1
PHP 5.6.30-0+deb8u1

If I manually map to manage-files.php, then I can upload files, view my account, etc.; but navigating to "View my files", leaves a blank screen. 
Using branch master.

I thought this might be related to #334, but when I make that change, the client logs in and immediately back out.

**Comment by macintyres** [comment] 2017-02-14 15:00
Downgraded to php 5.6
Still blank /my_files/
Like Patrick, I can manually input manage-files.php and access the menu bar.

**Comment by macintyres** [comment] 2017-02-14 15:23
I have the error logging in my php.ini set to default. The php errors I find are:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/2015012/msqli.so' - /usr/lib/php/2015012/msqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_mysql.dll' - /usr/lib/php/20151012/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_pgsql.dll' - /usr/lib/php/20151012/php_pdo_pgsql.dll: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by macintyres** [comment] 2017-02-14 15:50
I turned on display PHP errors. Purposely created an error on /my_files/index.php and got the appropriate error message. Then returned to the source index.php. I got a blank page with no error message.

**Comment by ilackskills** [comment] 2017-02-15 15:16
> Important Note: for version r608 and later you will need to enable PDO extension from php.ini
> 
> extension=php_pdo.dll
> extension=php_pdo_mysql.dll

**Comment by macintyres** [comment] 2017-02-15 15:35
Yes, those extensions are enabled.

**Comment by ilackskills** [comment] 2017-02-15 15:39
let me look at it, I have my_files disabled, dont use it.

**Comment by ilackskills** [comment] 2017-02-15 15:40
do you have php5-mysql installed?

`dpkg-query --status php5-mysql | grep Status
`

**Comment by macintyres** [comment] 2017-02-15 16:00
yes:

php5.6-mysql is already the newest version (5.6.30-1+deb.sury.org~xenial+1).

**Comment by ilackskills** [comment] 2017-02-15 16:02
I did not have 

> extension=php_pdo.dll
> extension=php_pdo_mysql.dll

in my INI but it is still not working, still working on the issue.

Do you have any errors on your blank page?

**Comment by ilackskills** [comment] 2017-02-15 16:08
My files as admin works as it should.  My files as client does not...Found it stand by.

**Comment by ilackskills** [comment] 2017-02-15 16:29
can you confirm My_files works as admin and not client.

**Comment by macintyres** [comment] 2017-02-15 16:41
Yes, I can access the my_files dir as admin. It displays correctly (e.g. menu,search, list of files,etc.)
Logged in as a client, my_files is a blank page and view source shows the "1"  line indicator only.

**Comment by ilackskills** [comment] 2017-02-15 17:03
OK there is an issue pre header, im working on it.

**Comment by ilackskills** [comment] 2017-02-15 17:48
/templates/session_check.php

**Line 14**
`if (isset($_SESSION['access']) && $_SESSION['access'] == CURRENT_USER_USERNAME) { $grant_access = 1; $is_client = 1; }`

**change to** 
`if (isset($_SESSION['access']) && $_SESSION['access'] == CURRENT_USER_USERNAME) { $grant_access = 1;}`

that fixes it but I am still working to figure out what is_client is

**Comment by patricksnead** [comment] 2017-02-15 18:14
That takes me back to #334 where the sql lookup fails. 

is_client = 1 is causing the sql lookup. 

We need a space trailing "FROM" and preceding "WHERE" perhaps? 
But also, looking at branch 756, the comparison used to be:
if ( $row['active'] == '0' )
but now in master it is just:
 if ( $row == '0' )

I'm thinking that's why I kept getting logged out.

**Comment by macintyres** [comment] 2017-02-15 18:26
Yay! progress! 
Wonder what is_client is for...

**Comment by ilackskills** [comment] 2017-02-15 18:43
glad i was able to help, wish i knew why that was even there...

**Comment by macintyres** [comment] 2017-02-15 18:55
Should I close this? And shouldn't it be classified as a bug? It doesn't seem to be a php version issue.

**Comment by ilackskills** [comment] 2017-02-15 18:57
I would say its closed as there is no call I can find for is_client, might be something unfinished.

**Closed** 2017-02-15 18:58 UTC
Labels: Configuration, PHP 5.6 + compatibilities

**Comment by gosymbian** [comment] 2020-05-03 08:14
Hi,
it's an old post but I have exactly the same problem, as admin it's ok but with a user, it goes directly to my_files with an empty page.
I have followed all the recomendation of this post, have changed the line in /templates/session_check.php without effect !

Any idea please ?
thanks,
Domi.

**Comment by ignacionelson** [comment] 2020-05-03 22:36
Hi @gosymbian 
It's possible this is due to a know error with the amount of results the template tries to show.
Try switching to the default template and let me know if it worked please.

**Comment by gosymbian** [comment] 2020-05-05 08:05
Hi Ignacio,
it works !! by switching the theme to the default but there were only 5 small files under the account, it's not very huge ! is it possible to fix that ?
Thnaks a lot !
have a nice day,
Domi.
