### ISSUE TITLE
New Version not working on Safari Browser

### ISSUE THREAD

**Issue by sgerhager** [ignacionelson/ProjectSend#550] opened 2018-04-25 07:47 UTC
The new navigation does not work on news Safari browser on current Mac OS X.
When clicking on Header in the navigation bar the unterlying navigation does not open.

**Comment by mschop** [comment] 2018-04-29 21:06
Do you see an error in the console log?

**Comment by mschop** [comment] 2018-05-27 18:06
@sgerhager I close this issue, as this seems to be a duplicate of #557 . Please follow the other issue for updates or reopen this issue, if the problem is different than the referenced issue.

**Closed by mschop** 2018-05-27 18:06 UTC
