### ISSUE TITLE
file overwriting

### ISSUE THREAD

**Issue by dannyulman** [ignacionelson/ProjectSend#315] opened 2016-12-21 03:00 UTC
When a file gets overwritten with same filename but different size it doesnt show up as a new upload.
So I have no idea that the customer uploaded a new version

The new version is getting uploaded and overwriting the old version but It still keeps the same file upload date and the same download count number.
I just found out because the customer called and wanted to know why his clients are not receiving their billing statements in the mail.
This is a really big problem.
I am going to lose this customer now.
What code can I change to fix this.

**Comment by zwobbl** [comment] 2016-12-21 15:17
this might be a duplicate to #305 

overwriting shouldn't happen. can you check that it is only an issue if the files are bigger than 1MB?

**Comment by lenamtl** [comment] 2016-12-22 14:46
Hi,

I'm not sure what is the real problem, could you tell what are the steps, so we can reproduce the problem. 
Include file size, file name and if this is for 1 client or a group.

Overwriting file should not occurred, so how this is happening on your side.

Client can get access to their file from the backend at any time so if they don't get the email, it's not a blocking issue. 
You cannot rely on email notification because it may not be sent for several reasons.
Your client should send manual email to notify for important file like an invoice. or for a follow up.

**Comment by ilackskills** [comment] 2017-02-08 21:59
I just had this happen to me just now.
First file was image.jpg
![image](https://cloud.githubusercontent.com/assets/15673241/22759265/678e1bb0-ee17-11e6-89cc-48acb18de195.png)

2nd file same file name 
![image](https://cloud.githubusercontent.com/assets/15673241/22759283/7974ebce-ee17-11e6-8a8d-0630bb951f4e.png)

**Comment by ilackskills** [comment] 2017-02-09 05:29
Temp Fix: **Use at your own risk**

On or around line 78, upload-from-computer.php
Change  chunk_size from 1mb to 0mb


![image](https://cloud.githubusercontent.com/assets/15673241/22770148/cffba226-ee53-11e6-9af3-a9aaa8fb905f.png)

http://www.plupload.com/docs/v2/Chunking

http://www.plupload.com/docs/v2/Frequently-Asked-Questions#when-to-use-chunking-and-when-not

>  So to sum this up - use chunking if:
> 
> you got to overcome server limitation on file size
> you will be uploading huge files, over 2gb (but be sure to omit Flash from list of potential runtimes in this case)
> you want to get smoother and more consistent upload progress across runtimes (but this will obviously slow down the upload itself, since there will be more work to do for each file)
> Do not use chunking if:
> 
> you need to upload huge files and absolutely require Flash to be in the list of fallback runtimes (in default mode Flash streams file directly from the disk, without preloading it in memory; other runtimes may survive this mode as well)


disabling this will limit the size of the file you are able to upload depending on your php.ini file settings, I will work on this more tomorrow.

**Comment by bugetarul** [comment] 2017-04-24 17:20
There are still problems when different clients upload the same name files
In the case of .doc and .pdf the problem is resolved, the file is rename _1 _2

But in the case of tif and rar they are overwriting

**Comment by lenamtl** [comment] 2017-04-26 14:23
Could you write steps to reproduce with real name file and extension including space uderscore ect
Thanks

**Comment by bugetarul** [comment] 2017-04-26 17:09
hello
2 users upload file with same name 01.tif
01.tif have 2,15 MB
01.tif have 3,17 MB
after upload remains a single file, the last upload.

the overwriting it's not happening in case of jpg or pdf
if 2 users uplod file with same name as 666_ro.pdf the file is rename as 666_ro_1.pdf, 666_ro_2.pdf
what is ok

There are other files that are not renamed as  .rar .zip

So renaming is good but does not apply to all files

**Comment by lenamtl** [comment] 2017-04-28 12:14
maybe because the file name start with a 0 
could you try with this name 666_ro.tiff

**Comment by zwobbl** [comment] 2017-04-28 13:38
@bugetarul are the jpg and pdf files that are not being overwritten less than 1MB in filesize?

**Comment by bugetarul** [comment] 2017-04-28 15:20
i try, is overwriting regardless of names.

**@zwobbl** You are right. All files are overwritten if larger than 1MB. Regardless of type, jpg, tif pdf....
And are renamed if they are under around 1 mb. Including tif

I want to make a repository for an event. And I expect everyone to send the files as "names-of-event. rar", or zip. The chances of doubling are very high

**Comment by zwobbl** [comment] 2017-04-28 17:25
then this is indeed a duplicate of #305

**Comment by bugetarul** [comment] 2017-04-28 17:51
Sorry about crossposting. 
What is the conclusion of 305?
Does not seem to be resolved

**Comment by ilackskills** [comment] 2017-04-29 04:10
@bugetarul to my knowledge this issue is not resolved.  Have you tried the work around?

**Comment by bugetarul** [comment] 2017-04-29 05:42
I lacks programming skills. :)

**Closed** 2017-05-01 00:18 UTC
Labels: Bug, Duplicate
